
spring:
  application:
    name: api-vr-curso-dev
  datasource:
    url: jdbc:h2:mem:dbvrcursoapi
    username: user
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
##
